CREATE SCHEMA [um]
GO

CREATE DATABASE [LinqDbTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LinqDbTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\LinqDbTest.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LinqDbTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\LinqDbTest_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LinqDbTest] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LinqDbTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LinqDbTest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LinqDbTest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LinqDbTest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LinqDbTest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LinqDbTest] SET ARITHABORT OFF 
GO

ALTER DATABASE [LinqDbTest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LinqDbTest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LinqDbTest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LinqDbTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LinqDbTest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LinqDbTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LinqDbTest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LinqDbTest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LinqDbTest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LinqDbTest] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LinqDbTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LinqDbTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LinqDbTest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LinqDbTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LinqDbTest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LinqDbTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LinqDbTest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LinqDbTest] SET RECOVERY FULL 
GO

ALTER DATABASE [LinqDbTest] SET  MULTI_USER 
GO

ALTER DATABASE [LinqDbTest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LinqDbTest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LinqDbTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LinqDbTest] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LinqDbTest] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LinqDbTest] SET  READ_WRITE 
GO

USE [LinqDbTest]
GO

CREATE TABLE [dbo].[Roles](
	[Id] [INT] IDENTITY(1,1) NOT NULL,
	[Name] [VARCHAR](100) NOT NULL,
	[Comment] [VARCHAR](1000) NULL,
	[IsLocked] [BIT] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [um].[Users](
	[Id] [INT] IDENTITY(1,1) NOT NULL,
	[FullName] [VARCHAR](100) NOT NULL,
	[IdentityName] [VARCHAR](100) NOT NULL,
	[RoleId] [INT] NOT NULL,
	[IsLocked] [BIT] NOT NULL,
	[LockReason] [VARCHAR](1000) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING ON
GO

ALTER TABLE [um].[Users]  WITH CHECK ADD  CONSTRAINT [FK_um_Users_um_Roles] FOREIGN KEY([RoleId])
REFERENCES [dbo].[Roles] ([Id])
GO

ALTER TABLE [um].[Users] CHECK CONSTRAINT [FK_um_Users_um_Roles]
GO


